name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  steps:
    - uses: actions/checkout@v1
    - name: setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Build and run tests
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        RAILS_ENV: TEST
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY}}
      run: |
        sudo apt-get -yqq install libpg-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:setup
        bundle exec rails test
